# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
# Local Costmap
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

static_map: false

# Sequence of plugin specifications, one per layer.
# Each specification is a dictionary with name and type fields.
# The name is used to define the parameter namespace for the plugin.
plugins:


- {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
- {name: inflation_layer, type: 'costmap_2d::InflationLayer'}


# Coordinate frame and tf parameters
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# The global frame for the costmap to operate in.
# (string, default: "/map")
global_frame: /bender/odom


# Rate parameters
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# The frequency in Hz for the map to be updated. 
# update_frequency (double, default: 5.0)
update_frequency: 5.0

# The frequency in Hz for the map to be publish display information. 
# publish_frequency (double, default: 0.0)
publish_frequency: 0.0


# Map management parameters
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

# Whether or not to use a rolling window version of the costmap. If the 
# static_map parameter is set to true, this parameter must be set to false. 
# rolling_window (bool, default: false)
rolling_window: true

# If true the full costmap is published to "~<name>/grid" every update. If 
# false only the part of the costmap that has changed is published on the 
# "~<name>/grid_updates" topic. 
# always_send_full_costmap (bool, default: false)
always_send_full_costmap: false
    
# The following parameters can be overwritten by some layers, namely the 
# static map layer:
#
# - The width of the map in meters.           (int, default: 10)
# - The height of the map in meters.          (int, default: 10)
# - The resolution of the map in meters/cell. (double, default: 0.05)
# - The x origin of the map in the global frame in meters. (double, default: 0.0)
# - The y origin of the map in the global frame in meters. (double, default: 0.0)
# 
width: 5
height: 5
resolution: 0.025
origin_x: 0.0
origin_y: 0.0
