
# if not specified, all parameters are in [m],[s] 

# tf info
map_frame: "/map"
base_frame: "/bender/base_link"
tf_buffer_size: 3.0

# tracking parameters
goal_almost_reach_radius: 0.3
goal_reach_degree_th: 10.0

# listen topics 
pose_topic: "/bender/nav/amcl_pose"
goal_topic: "/bender/nav/goal_server/goal"
obstacles_topic: "/bender/nav/move_base/global_costmap/inflated_obstacles"

# where to publish the initial pose
input_initial_pose_topic: "/bender/nav/goal_server/initialpose"
output_initial_pose_topic: "/bender/nav/initialpose"

# where to obtain the map
map_service: "/static_map"



# for approach to person service
# - - - - - - - - - - - - - - - - - - -
approach_delta_degree: 15.0
approach_delta_radius: 0.8
approach_max_radius: 1.1
approach_person_radius: 1.0
approach_window_w: 0.8
approach_window_h: 0.8

# max length from point to obstacle
approach_obstacle_th: 0.02

# max number of unknown points in map
approach_unknown_th: 10

# - - - - - - - - - - - - - - - - - - -

goal_spread_x: 0.25
goal_spread_y: 0.25
goal_spread_theta: 0.20