# common costmap:
 # common parameters for the local and global
 # costmaps used by the move_base node

 # Coordinate frame and tf parameters
 # - - - - - - - - - - - - - - - - - -
 robot_base_frame: /bender/base_link
 transform_tolerance: 0.5
 # global_frame: costmap dependent

 # Rate parameters
 # - - - - - - - - - - - - - - - - - -
 # costmap dependent

 # Map management parameters
 # - - - - - - - - - - - - - - - - - -
 # map_type: {voxel or costmap}
 map_type: costmap # (ahora "voxel" es el  default.. de hecho, "costmap" ya no esta documentado)
 # origin_x: 0.0   /* default */
 # origin_y: 0.0   /* default */


 # Static Map Layer
 # = = = = = = = = = = = = = = = = = = 
 # unknown_cost_value: 0       /* default */
 # lethal_cost_threshold: 100  /* default */
 # map_topic: map              /* default */



 # Obstacle Map Layer
 # = = = = = = = = = = = = = = = = = = 

 # Sensor management parameters
 # - - - - - - - - - - - - - - - - - - 
 # hay que tomar en cuenta, que si el rgbd est'a en otro pc, la carga de datos ser'a mucha!!

 #observation_sources: "laser_front_sensor laser_rear_sensor"
 observation_sources: "laser_front_sensor laser_rear_sensor rgbd_head_scan_sensor"

 # required to work
 laser_front_sensor: {
  sensor_frame: /bender/sensors/laser_front_link,
  data_type: LaserScan,
  topic: /bender/sensors/laser_front/scan_filtered,
  marking: true,
  clearing: true,
  expected_update_rate: 0.1,
  obstacle_range: 15,
  raytrace_range: 16,
  observation_persistence: 0.2
 }

 # optional
 laser_rear_sensor: {
  sensor_frame: /bender/sensors/laser_rear_link,
  data_type: LaserScan,
  topic: /bender/sensors/laser_rear/scan,
  marking: true,
  clearing: true,
  expected_update_rate: 0.0,
  obstacle_range: 3.4,
  raytrace_range: 3.5,
  observation_persistence: 0.2
 }

 # rgbd_head to laserscan
 rgbd_head_scan_sensor: {
  sensor_frame: bender/sensors/rgbd_head_laser_link,
  data_type: LaserScan,
  topic: /bender/sensors/rgbd_head/depth/scan,
  marking: true,
  clearing: true,
  #expected_update_rate: 0.1,
  obstacle_range: 2.9,
  raytrace_range: 3,
  max_obstacle_height: 1,
  min_obstacle_height: 0.0,
  #observation_persistence: 5
 }

 # optional
 #rgbd_head_sensor: {
 # sensor_frame: bender/sensors/rgbd_head_rgb_optical_frame,
 # data_type: PointCloud2,
 # topic: /bender/sensors/rgbd_head/depth/points,
 # marking: true,
 # clearing: true,
 # expected_update_rate: 0.0,
 # obstacle_range: 3.5,     # TODO: fix this (currently using a dummy value)
 # raytrace_range: 3.5,     # TODO: fix this (currently using a dummy value)
 # max_obstacle_height: 2.0,
 # min_obstacle_height: 0.04,
 # observation_persistence: 2
 #}


 # Global Filtering params
 # - - - - - - - - - - - - - - - - - -
 # (apply to all sensors)

 # overrides higher per-sensor configs
 max_obstacle_height: 2.0
 # obstacle_range:  overriden on a per-sensor basis
 # raytrace_range:  overriden on a per-sensor basis


 # Obstacle Costmap Plugin (2D)
 # - - - - - - - - - - - - - - - - - -
 # (only used by the ObstacleCostmapPlugin)
 # Specifies whether or not to track what space in the costmap is unknown,
 # meaning that no observation about a cell has been seen from any sensor source.
 # WARNING: when setting this to true, the robot will fail to move at starting
 # because there will not be any information about its environment.
 # to solve this, you would need to move the base on your own before attempting to make a plan.
 track_unknown_space: false


 # Voxel Costmap Plugin    (3D)
 # - - - - - - - - - - - - - - - - - -
 # (only used by the VoxelCostmapPlugin)
 #origin_z: 0.0       #
 #z_resolution: 0.2   #
 #z_voxels: 10        #
 #unknown_threshold:  # (default: z_voxels)
 #mark_threshold: 0   #
 #publish_voxel_map: true # /* underlying volxel grid (visualization purposes) */

 # Inflation Layer
 # = = = = = = = = = = = = = = = = = = 
 # ... 
